services:
  fastapi:
    public: true
    build: .
    replicas: 1
    environment:
      - REDIS_URI=redis://torrent:U6dL75O7CTYNqgkuzNwIWFyWcy6k709Q@redis-15526.c275.us-east-1-4.ec2.cloud.redislabs.com:15526 #change this REDIS_URI get it from redistogo.com
      - PYTHON_ENV=prod
      - CACHE_EXPIRATION=180
    ports:
      - 8080
    resources:
      requests:
        cpu: 500m
        memory: 1500Mi
      limits:
        cpu: 1000m
        memory: 3000Mi
