services:
  fastapi:
    public: true
    build: .
    replicas: 1
    environment:
      - REDIS_URI=redis://default:SLiLqL68ZgiftgBGVMqu@containers-us-west-33.railway.app:6695 #change this REDIS_URI get it from redistogo.com
      - PYTHON_ENV=prod
      - CACHE_EXPIRATION=180
    ports:
      - 8080
    resources:
      requests:
        cpu: 500m
        memory: 1500Mi
      limits:
        cpu: 1000m
        memory: 3000Mi
